from DB_functions import load_customers_with_available_terminals_from_csv, load_terminals_from_csv, clear_database, load_transactions_from_csv

clear_database()

load_terminals_from_csv()

load_customers_with_available_terminals_from_csv()

load_transactions_from_csv()